name: Java CI with Maven

on:
  push:
    branches: [ main, "fix/**", "feature/**" ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Make mvnw executable
        run: chmod +x ./mvnw

      - name: Build — compilar todos los módulos
        run: ./mvnw clean package -DskipTests --no-transfer-progress

      - name: Run Tests — pruebas automáticas
        run: ./mvnw test --no-transfer-progress